### ISSUE TITLE
git.apache.org/thrift.git cann't access so error when build.

### ISSUE THREAD

**Issue by chithanh89** [kbudde/rabbitmq_exporter#145]
Hi guys,

git.apache.org/thrift.git cann't access to get go module, i replace it in go.mod with github.com/apache/thrift and removed 2 line: git.apache.org/thrift.git v0.0.0 in go.sum but when i run go get it's still find git.apache.org/thrift.git v0.0.0 >> error.
Can someone help me resolve this?

**Comment by kbudde** [comment]
Ok,

I've faced now the same issue. There are many repos outside having the same issue.
I've upgraded go to version 1.13 which is using module proxy and fixing the issue without changes on dependency tree.

I will try to update dependencies in a second step. Perhaps the issue was already fixed upstream.
