### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by llech** [kbudde/rabbitmq_exporter#251]
Do you have a helm chart for kbudde/rabbitmq_exporter?

Official or unofficial?

It's not hard to write, but I'd prefer not to reinvent the wheel.

**Comment by kbudde** [comment]
Hi, there is an unofficial chart https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-rabbitmq-exporter which looks quite good.
This chart uses version 0.29 of this exporter. It's a bit old but it is the last version which is able to scrape the rabbitMQ through a loadbalancer (k8s service). 

The latest version needs #230 to be implemented. There were not so many requests in the past.
Since RabbitMQ now has its own plugin for metrics, the priority is currently rather low.
