### ISSUE TITLE
undefined: bert.Map

### ISSUE THREAD

**Issue by ton31337** [kbudde/rabbitmq_exporter#34]
With the latest master branch:

```
# _/opt/prometheus/rabbitmq_exporter
./bertmap.go:89: undefined: bert.Map
./bertmap.go:90: cannot range over obj (type interface {})
```

**Comment by kbudde** [comment]
Hi,

I'm not able to reproduce the issue. 
Did you compile the binary yourself? Which go version are you using?
All dependencies are vendored. Since Go 1.6 you should not have any issues.

BR

Kris

**Comment by ton31337** [comment]
All good if using newer Go or compiled version 👍

**Comment by vineetsharma02** [comment]
Hi ton31337,
  
   Can you please let me know which go version are you using. I tried almost 3-4 versions but still same error.

rabbitmq_exporter# go build
# _/root/rabbitmq_exporter
./bertmap.go:89: undefined: bert.Map
./bertmap.go:90: cannot range over obj (type interface {})
rabbitmq_exporter# go version
go version go1.7.6 linux/amd64

Regards,
Vineet

**Comment by kbudde** [comment]
Hi,

For building the exporter yourself you have to checkout the repository to
your gopath.

All dependencies are vendored. This is just working since go 1.5/1.6 and if
you are in your gopath.
https://github.com/golang/go/issues/14566

There is also a makefile using Docker for building.

BR

Kris

Am 12.06.2017 17:32 schrieb "vineet sharma" <notifications@github.com>:
