### ISSUE TITLE
Not an issue - Rabbit MQ Exporter

### ISSUE THREAD

**Issue by jinsr65** [kbudde/rabbitmq_exporter#37]
The exporter here , is it only for rabbit mq deployed through docker or would this pull metrics from rabbit mq software deployed on local.

**Comment by kbudde** [comment]
Hi,

It can be used with the normal rabbit mq installation as well. Just the
management api plugin and a username and password are needed.

I have both setups running.

BR Kris

Am 02.08.2017 23:12 schrieb "jinsr65" <notifications@github.com>:

The exporter here , is it only for rabbit mq deployed through docker or
would this pull metrics from rabbit mq software deployed on local.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kbudde/rabbitmq_exporter/issues/37>, or mute the thread

**Comment by jinsr65** [comment]
Thanks a lot for taking the time to respond to this.
