### ISSUE TITLE
CPU consumption on scrape

### ISSUE THREAD

**Issue by zarkoc** [kbudde/rabbitmq_exporter#50]
Hi guys,

Im running the latest release v0.23.0.
The cpu get highly consumed whenever a scrape is done.
We have 28 queues that are being scraped.

Is this something that is know to happen, is there a way to fix it?

Thanks,
Zarko

**Comment by kbudde** [comment]
Hi,

for 28 queues you should not see a high cpu usage.
Which RABBIT_EXPORTERS are configured (default?)
Do you have many exchanges?

From my experience you can see higher cpu usage during scraping for some hundreds of queues caused by exporter and rabbitmq together.
But for 28 queues you should not see any hit on cpu. 

For RabbitMQ version 3.6.8 and newer you should set RABBIT_CAPABILITIES="no_sort". Which will reduce the overhead on rabbitmq management plugin a bit.
For 3.6.9 and newer you should set RABBIT_CAPABILITIES="no_sort,bert". This will use bert instead of json. This should reduce the overhead on both RabbitMQ and exporter for de/encoding json.

**Comment by kbudde** [comment]
Hi,
I've optimized cpu usage. Perhaps you can try the latest commit on master.
It should speed up the exporter for your use case by ~ 40%. Cpu usage should be decreased as well.
If possible use the no_sort option.

Using bert will slow down the exporter (factor 2). I'm have to investigate the cpu usage for bert as well.

**Comment by zarkoc** [comment]
Thanks Kris,

Im on rabbitmq 3.6.10, iv set the RABBIT_CAPABILITIES=no_sort,bert.

Ill try the new version and let you know the results (i'll remove bert from the capabilites).

Thanks
Zarko

**Comment by zarkoc** [comment]
Hey Kris,

It's speeded up around 3 times. The scrape that lasted 6sec, now lasts 2sec and sometime bellow a second. The cpu still get 50 to 60% utilizes but its much better that before when it went to 100% for almost a second.

On the other note I was bind, I have **1501** queues that are getting reported by the exporter. And I'm only filtering 28...

Zarko

**Comment by kbudde** [comment]
Hi,

there were some work for the bert library. Testing with 500 queues, bert will now just need 75% of the time compared to json. And hopefully less cpu consuming as well.
Therefore I would recommend using the latest commit and the RABBIT_CAPABILITIES=no_sort,bert again.

Can you please test it?
If its okay for you, I would close the issue and create a release.

Best regards

Kris Budde

**Comment by zarkoc** [comment]
Hi Kirs,

Im testing it. I'll let you know the results today.

Tx.
Zarko

**Comment by zarkoc** [comment]
Hey Kris,

Sorry for the late response, everything is ok now.
