### ISSUE TITLE
Include exchange name in queue metrics

### ISSUE THREAD

**Issue by dimrozakis** [kbudde/rabbitmq_exporter#52]
Is this possible? It'd make it much easier to filter queues per exchange.

**Comment by kbudde** [comment]
Hi,

a queue can be bound to many exchanges and in some use cases may be dynamic.
So it would be a list of exchanges in the queue metric. I would not recommend doing it like this.

I would recommend naming conventions for queues for filtering instead of adding more labels.
Btw. there are as well some exchange metrics which might be interesting for you.

BR

Kris

**Comment by dimrozakis** [comment]
thanks!
