### ISSUE TITLE
rabbitmq_up == 1 for rabbitmq ok, ==0 for rabbitmq down?

### ISSUE THREAD

**Issue by szediktam** [kbudde/rabbitmq_exporter#76]
when the metircs rabbitmq_up is equal to 1, it means that rabbitmq server is ok.while 0, it means rabbitmq server is down. Is it right?

**Comment by kbudde** [comment]
Hi,

if the up metric is 1 it means that all endpoints were successfully scrapped.
0 means that there was an issue retrieving the data from rabbitmq. Which could mean that the server was down or a problem in the network or with authentication.

For monitoring one or more nodes you should check the [node metrics](https://github.com/kbudde/rabbitmq_exporter#node---counter)

**Comment by szediktam** [comment]
Thank you for your reply.
I use rabbitmq_exporter to monitor rabbimq server. If rabbitmq_up ==1, it is up; if 0, it is problem or down.
I have 3 replicas on 3 nodes, rabbitmq_running == 1 shows that rabbitmq server on this node is ok?

**Comment by szediktam** [comment]
BTY, I encountered a problem that timeout when get /api/queues, similar to #68 . the erroe as following:
time="2018-04-10T08:36:57Z" level=error msg="Error while retrieving data from rabbitHost" error="Get http://rabbitmq.openstack.svc.cluster.local:15672/api/queues: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" host="http://rabbitmq.openstack.svc.cluster.local:15672" statusCode=0

May be the timeout= 15s is not long enough. In my env, it takes 20-30s.

How to compile rabbitmq_exporter. I want to increase the time to test it.

**Comment by glend** [comment]
I have the same issue because of the timeout, the rabbitmq API takes more to respond sometimes and I get timeout issues.

I set prometheus to scrape every 30s and it works but rabbitmq_up stays 0, even though other metrics are collected.

**Comment by szediktam** [comment]
You can increase the timeout of http.Client (2 places) in rabbitmq_exporter/rabbitClient.go. And execute "make docker" to make a new images. I increase timeout to 60s, and it works fine.

But rabbitmq-exporter target may be Down by "context deadline exceeded". Increasing the scrape_timeout of Prometheus may be a solution.

**Comment by lunaqdm** [comment]
@kbudde would it be possible to add a flag to manually set the timeout? I am not sure I understand how the timeout is set right now -- on the one hand, from glancing at the code, it looks like the default timeout is 15s. However, from some of your responses to questions, it does seem that the timeout depends on how often Prometheus scrapes the endpoint.

Why I ask: Prometheus keeps claiming that the RabbitMQ Exporter is down, and when I look at the RabbitMQ Exporter logs I see:

time="2018-04-12T23:09:37Z" level=error msg="Error while retrieving data from rabbitHost" error="Get http://rabbitmq.<company-specific>.io:80/api/exchanges?sort=: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" host="http://rabbitmq.<company-specific>.io:80" statusCode=0

I have set my Prometheus scrape interval to 30s and timeout to 15s. I just increased both to 60s, so that may help significantly -- we'll see.

Thanks so much for your responsiveness to all my questions, and for building such a useful tool!

**Comment by szediktam** [comment]
hi @kbudde  
I want to low the scrape frequency  and increase the scrape internal from rabbitmq-exporter to rabbmitmq-server. Where to modify the config?
Thank you.

**Comment by kbudde** [comment]
Hi,

the exporter is retriving the data from rabbitmq server just if prometheus is calling the metrics endpoint.
So there is no config needed; you just need to reconfigure prometheus scrape_intervall for the exporter.

**Comment by hypery2k** [comment]
having this issue
